# Generated by Django 5.2.8 on 2025-11-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_core', '0001_initial'),
        ('xero_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroJournalsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.CharField(max_length=51)),
                ('journal_number', models.IntegerField()),
                ('collection', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals_sources', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['organisation', 'journal_number'],
            },
        ),
        migrations.CreateModel(
            name='XeroTransactionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_id', models.CharField(max_length=51, unique=True)),
                ('transaction_source', models.CharField(max_length=51)),
                ('collection', models.JSONField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_sources', to='xero_metadata.xerocontacts')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sources', to='xero_core.xerotenant')),
            ],
        ),
        migrations.CreateModel(
            name='XeroJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.CharField(max_length=51)),
                ('journal_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='xero_metadata.xeroaccount')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='xero_core.xerotenant')),
                ('tracking1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals_track1', to='xero_metadata.xerotracking')),
                ('tracking2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals_track2', to='xero_metadata.xerotracking')),
                ('journal_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='xero_data.xerojournalssource')),
                ('transaction_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='xero_data.xerotransactionsource', to_field='transactions_id')),
            ],
            options={
                'ordering': ['organisation', 'date', 'journal_number'],
            },
        ),
        migrations.AddIndex(
            model_name='xerojournalssource',
            index=models.Index(fields=['organisation', 'processed'], name='jrnl_src_org_proc_idx'),
        ),
        migrations.AddIndex(
            model_name='xerojournalssource',
            index=models.Index(fields=['organisation', 'journal_number'], name='jrnl_src_org_num_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xerojournalssource',
            unique_together={('organisation', 'journal_id')},
        ),
        migrations.AlterUniqueTogether(
            name='xerotransactionsource',
            unique_together={('organisation', 'transactions_id')},
        ),
        migrations.AddIndex(
            model_name='xerojournals',
            index=models.Index(fields=['organisation', 'date'], name='journals_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='xerojournals',
            index=models.Index(fields=['organisation', 'account'], name='journals_org_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='xerojournals',
            index=models.Index(fields=['organisation', 'date', 'account'], name='journals_org_dt_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='xerojournals',
            index=models.Index(fields=['date'], name='journals_date_idx'),
        ),
        migrations.AddIndex(
            model_name='xerojournals',
            index=models.Index(fields=['organisation', 'transaction_source'], name='journals_org_txn_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xerojournals',
            unique_together={('organisation', 'journal_id')},
        ),
    ]
