# Generated by Django 5.2.8 on 2025-11-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_core', '0001_initial'),
        ('xero_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroTrailBalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date of the report')),
                ('report_type', models.CharField(default='TrialBalance', help_text='Type of report from Xero', max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='When this report was imported')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw JSON data from Xero API', null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_trail_balance_reports', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['-report_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='TrailBalanceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_value', models.DecimalField(decimal_places=2, help_text='Value from Xero report', max_digits=30)),
                ('db_value', models.DecimalField(decimal_places=2, help_text='Value from our database', max_digits=30)),
                ('difference', models.DecimalField(decimal_places=2, help_text='Difference (xero_value - db_value)', max_digits=30)),
                ('match_status', models.CharField(choices=[('match', 'Match'), ('mismatch', 'Mismatch'), ('missing_in_db', 'Missing in DB'), ('missing_in_xero', 'Missing in Xero')], help_text='Status of the comparison', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the comparison')),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_balance_comparisons', to='xero_metadata.xeroaccount')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='xero_validation.xerotrailbalancereport')),
            ],
            options={
                'ordering': ['-difference', 'account__code'],
            },
        ),
        migrations.CreateModel(
            name='XeroTrailBalanceReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(help_text='Account code from Xero', max_length=50)),
                ('account_name', models.CharField(help_text='Account name from Xero', max_length=255)),
                ('account_type', models.CharField(blank=True, help_text='Account type from Xero', max_length=50, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount (YTD if available, else period)', max_digits=30)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount (YTD if available, else period)', max_digits=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Net value (debit - credit)', max_digits=30)),
                ('period_debit', models.DecimalField(decimal_places=2, default=0, help_text='Period debit amount', max_digits=30)),
                ('period_credit', models.DecimalField(decimal_places=2, default=0, help_text='Period credit amount', max_digits=30)),
                ('ytd_debit', models.DecimalField(decimal_places=2, default=0, help_text='YTD debit amount (cumulative)', max_digits=30)),
                ('ytd_credit', models.DecimalField(decimal_places=2, default=0, help_text='YTD credit amount (cumulative)', max_digits=30)),
                ('db_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value calculated from database (e.g., P&L from XeroTrailBalance)', max_digits=30, null=True)),
                ('row_type', models.CharField(blank=True, help_text='Row type (e.g., Header, Row, SummaryRow)', max_length=50, null=True)),
                ('raw_cell_data', models.JSONField(blank=True, help_text='Raw cell data from Xero API', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xero_report_lines', to='xero_metadata.xeroaccount')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='xero_validation.xerotrailbalancereport')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.AddIndex(
            model_name='xerotrailbalancereport',
            index=models.Index(fields=['organisation', 'report_date'], name='xero_tb_rpt_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='trailbalancecomparison',
            index=models.Index(fields=['report', 'match_status'], name='xero_tb_comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trailbalancecomparison',
            index=models.Index(fields=['report', 'account'], name='xero_tb_comp_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='xerotrailbalancereportline',
            index=models.Index(fields=['report', 'account_code'], name='xero_tb_rpt_line_code_idx'),
        ),
        migrations.AddIndex(
            model_name='xerotrailbalancereportline',
            index=models.Index(fields=['report', 'account'], name='xero_tb_rpt_line_acc_idx'),
        ),
    ]
