# Generated by Django 5.2.8 on 2025-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_validation', '0002_add_profit_loss_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotrailbalancereport',
            name='parsed_json',
            field=models.JSONField(blank=True, help_text='Parsed JSON data from trial balance parser', null=True),
        ),
    ]
