# Generated by Django 5.2.8 on 2025-11-20 17:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroTenantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable scheduled tasks for this tenant')),
                ('update_interval_minutes', models.IntegerField(default=60, help_text='Minutes between update runs')),
                ('update_start_time', models.TimeField(default=datetime.time(0, 0), help_text='Preferred start time for updates')),
                ('last_update_run', models.DateTimeField(blank=True, help_text='Last time update task ran', null=True)),
                ('last_process_run', models.DateTimeField(blank=True, help_text='Last time process task ran', null=True)),
                ('next_update_run', models.DateTimeField(blank=True, help_text='Next scheduled update run', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['tenant__tenant_name'],
            },
        ),
        migrations.CreateModel(
            name='XeroLastUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_updates', to='xero_core.xerotenant')),
            ],
            options={
                'unique_together': {('organisation', 'end_point')},
            },
        ),
        migrations.CreateModel(
            name='XeroTaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('update_models', 'Update Models'), ('process_data', 'Process Data')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Task duration in seconds', null=True)),
                ('records_processed', models.IntegerField(blank=True, help_text='Number of records processed', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Additional statistics (e.g., API calls, DB queries)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant', 'task_type', 'status'], name='task_log_tenant_type_idx'), models.Index(fields=['tenant', 'started_at'], name='task_log_tenant_date_idx'), models.Index(fields=['status', 'started_at'], name='task_log_status_date_idx')],
            },
        ),
    ]
