# Generated by Django 5.2.8 on 2025-11-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0002_enhance_last_update_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerolastupdate',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Legacy field - use end_time instead', null=True),
        ),
        migrations.AlterField(
            model_name='xerolastupdate',
            name='end_point',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('contacts', 'Contacts'), ('tracking_categories', 'Tracking Categories'), ('journals', 'Journals'), ('manual_journals', 'Manual Journals'), ('profit_loss', 'Profit & Loss')], max_length=100),
        ),
    ]
