# Generated by Django 5.2.8 on 2025-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0001_initial'),
        ('xero_sync', '0004_create_process_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerolastupdate',
            name='name',
            field=models.CharField(blank=True, help_text='Optional unique name/identifier for this update record', max_length=200, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='xerolastupdate',
            index=models.Index(fields=['name'], name='last_update_name_idx'),
        ),
    ]
