# Generated by Django 5.2.8 on 2025-11-21 15:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0005_add_name_to_xerolastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTreeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable scheduled execution for this process tree')),
                ('interval_minutes', models.IntegerField(default=60, help_text='Minutes between executions')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), help_text='Preferred start time for executions')),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time this process tree was executed', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Next scheduled execution time', null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Default context to pass to the process tree execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_tree', models.OneToOneField(help_text='The process tree to schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='xero_sync.processtree')),
            ],
            options={
                'ordering': ['process_tree__name'],
                'indexes': [models.Index(fields=['enabled', 'next_run'], name='process_tree_schedule_idx')],
            },
        ),
    ]
