# Generated by Django 5.2.8 on 2025-11-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0006_add_process_tree_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name/identifier for this trigger', max_length=200, unique=True)),
                ('trigger_type', models.CharField(choices=[('condition', 'Condition'), ('schedule', 'Schedule'), ('event', 'Event'), ('custom', 'Custom Function'), ('outdated_check', 'Outdated Data Check')], default='condition', help_text='Type of trigger', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this trigger is enabled')),
                ('description', models.TextField(blank=True, help_text='Description of what this trigger checks')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Trigger configuration/parameters')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last time this trigger was checked', null=True)),
                ('last_triggered', models.DateTimeField(blank=True, help_text='Last time this trigger fired (returned True)', null=True)),
                ('trigger_count', models.IntegerField(default=0, help_text='Number of times this trigger has fired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_tree', models.ForeignKey(blank=True, help_text='Optional ProcessTree this trigger is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='xero_sync.processtree')),
                ('xero_last_update', models.ForeignKey(blank=True, help_text='Optional XeroLastUpdate record for outdated checks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='xero_sync.xerolastupdate')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'trigger_type'], name='trigger_enabled_type_idx'), models.Index(fields=['process_tree', 'enabled'], name='trigger_tree_enabled_idx')],
            },
        ),
    ]
