# Generated by Django 5.2.8 on 2025-11-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0007_add_trigger_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='last_fired_manually',
            field=models.DateTimeField(blank=True, help_text='Last time this trigger was manually fired by external process', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired'), ('reset', 'Reset')], default='pending', help_text='Current state of the trigger (can be set by external processes)', max_length=20),
        ),
        migrations.AddField(
            model_name='trigger',
            name='subscribed_trees',
            field=models.ManyToManyField(blank=True, help_text='Process trees that subscribe to this trigger', related_name='subscribed_triggers', to='xero_sync.processtree'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='process_tree',
            field=models.ForeignKey(blank=True, help_text='Optional ProcessTree this trigger is associated with (legacy - use subscriptions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='xero_sync.processtree'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['state', 'enabled'], name='trigger_state_enabled_idx'),
        ),
    ]
