# Generated by Django 5.2.8 on 2025-11-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0008_add_trigger_subscriptions_and_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='subscribed_trees',
        ),
        migrations.AddField(
            model_name='processtree',
            name='trigger',
            field=models.ForeignKey(blank=True, help_text='Trigger this process tree subscribes to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_trees', to='xero_sync.trigger'),
        ),
    ]
