# Generated by Django 5.2.8 on 2025-11-25 16:27

from django.db import migrations, models


def migrate_end_time_to_date(apps, schema_editor):
    """Migrate end_time values to date field before removing end_time."""
    XeroLastUpdate = apps.get_model('xero_sync', 'XeroLastUpdate')
    for update in XeroLastUpdate.objects.all():
        if update.end_time and not update.date:
            update.date = update.end_time
            update.save(update_fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0009_change_trigger_to_one_to_many'),
    ]

    operations = [
        # First, migrate data from end_time to date
        migrations.RunPython(migrate_end_time_to_date, migrations.RunPython.noop),
        # Then remove indexes and fields
        migrations.RemoveIndex(
            model_name='xerolastupdate',
            name='last_update_org_sync_idx',
        ),
        migrations.RemoveField(
            model_name='xerolastupdate',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='xerolastupdate',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='xerolastupdate',
            name='out_of_sync',
        ),
        migrations.RemoveField(
            model_name='xerolastupdate',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='xerolastupdate',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Last successful update timestamp', null=True),
        ),
    ]
