# Generated by Django 5.2.8 on 2025-11-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_core', '0001_initial'),
        ('xero_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets_accounts', to='xero_metadata.xeroaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='balance_sheets', to='xero_metadata.xerocontacts')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='xero_core.xerotenant')),
            ],
            options={
                'unique_together': {('organisation', 'account', 'contact', 'date')},
            },
        ),
        migrations.CreateModel(
            name='XeroTrailBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('fin_year', models.IntegerField()),
                ('fin_period', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_balances', to='xero_metadata.xeroaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trail_balances', to='xero_metadata.xerocontacts')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_balances', to='xero_core.xerotenant')),
                ('tracking1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trail_balances_track1', to='xero_metadata.xerotracking')),
                ('tracking2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trail_balances_track2', to='xero_metadata.xerotracking')),
            ],
            options={
                'ordering': ['organisation', 'account', 'year', 'month', 'contact'],
                'indexes': [models.Index(fields=['organisation', 'year', 'month'], name='tb_org_ym_idx'), models.Index(fields=['organisation', 'account', 'year', 'month'], name='tb_org_acc_ym_idx'), models.Index(fields=['account', 'contact'], name='tb_acc_contact_idx'), models.Index(fields=['organisation', 'account', 'contact'], name='tb_org_acc_ct_idx'), models.Index(fields=['year', 'month'], name='tb_ym_idx')],
            },
        ),
    ]
