# Generated by Django 5.2.8 on 2025-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_cube', '0002_add_balance_to_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerotrailbalance',
            name='balance_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance to date for P&L accounts (REVENUE/EXPENSE) - cumulative sum of all previous months up to and including current month', max_digits=30, null=True),
        ),
    ]
