# Generated by Django 5.2.8 on 2025-11-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_url', models.CharField(max_length=255)),
                ('refresh_url', models.CharField(max_length=255)),
                ('auth_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='XeroClientCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('scope', models.JSONField(blank=True)),
                ('token', models.JSONField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_client_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XeroTenantToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.JSONField()),
                ('refresh_token', models.CharField(max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_tokens', to='xero_auth.xeroclientcredentials')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_tokens', to='xero_core.xerotenant')),
            ],
            options={
                'unique_together': {('tenant', 'credentials')},
            },
        ),
    ]
