# Generated by Django 5.2.8 on 2025-11-21 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_auth', '0002_add_tenant_tokens_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerotenanttoken',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_tenant_tokens', to='xero_auth.xeroclientcredentials'),
        ),
    ]
