# Generated by Django 5.2.8 on 2025-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XeroTenant',
            fields=[
                ('tenant_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tenant_name', models.CharField(max_length=100)),
            ],
        ),
    ]
