# Generated by Django 5.2.8 on 2025-11-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroBusinessUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_code', models.CharField(blank=True, max_length=1, null=True)),
                ('business_unit_code', models.CharField(max_length=1)),
                ('division_description', models.CharField(blank=True, max_length=100, null=True)),
                ('business_unit_description', models.CharField(max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='xero_core.xerotenant')),
            ],
            options={
                'unique_together': {('organisation', 'business_unit_code', 'division_code')},
            },
        ),
        migrations.CreateModel(
            name='XeroAccount',
            fields=[
                ('account_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('reporting_code', models.TextField(blank=True)),
                ('reporting_code_name', models.TextField(blank=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=40, null=True)),
                ('grouping', models.CharField(blank=True, max_length=30)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('collection', models.JSONField(blank=True, null=True)),
                ('attr_entry_type', models.CharField(blank=True, max_length=30, null=True)),
                ('attr_occurrence', models.CharField(blank=True, max_length=30, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='xero_core.xerotenant')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xero_metadata.xerobusinessunits')),
            ],
            options={
                'ordering': ['organisation', 'code'],
                'indexes': [models.Index(fields=['organisation', 'code'], name='acc_org_code_idx'), models.Index(fields=['organisation', 'type'], name='acc_org_type_idx'), models.Index(fields=['organisation', 'business_unit'], name='acc_org_bu_idx')],
                'unique_together': {('organisation', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='XeroContacts',
            fields=[
                ('contacts_id', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('collection', models.JSONField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['organisation', 'name'],
                'unique_together': {('organisation', 'contacts_id')},
            },
        ),
        migrations.CreateModel(
            name='XeroTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.TextField(max_length=1024)),
                ('name', models.TextField(blank=True, max_length=1024, null=True)),
                ('option', models.TextField(blank=True, max_length=1024, null=True)),
                ('collection', models.JSONField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['organisation', 'option'],
                'unique_together': {('organisation', 'option_id')},
            },
        ),
    ]
